services:
  owui-llama-cpp-runner-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: owui-llama-cpp-runner-gpu
    ports:
      - "10000:10000"  # Using different port from CPU version
    environment:
      - MODELS_DIR=/models
      - CACHE_DIR=/cache
      - VERBOSE=true
      - TIMEOUT_MINUTES=30
      - ENABLE_GPU=true
      - GPU_LAYERS=-1 
      - CUDA_VISIBLE_DEVICES=0  # Specify which GPU to use (0 is the first GPU)
      - LD_LIBRARY_PATH=/cache/llama_cpp/build/lib:/cache/llama_cpp/build/bin:/usr/local/cuda/lib64:/usr/lib
    volumes:
      - ./models:/models  # local mount for models
      - ./cache:/cache    # local mount for cache
      - ./scripts:/app/scripts  # mount scripts directory
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]  # Fixed port to match the actual service
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s