version: '3.8'

services:
  llama-cpp-runner:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: llama-cpp-runner
    ports:
      - "10000:10000"
    volumes:
      - ./models:/models # local mount for models
      - ./cache:/cache   # local mount for cache
    environment:
      - MODELS_DIR=/models
      - CACHE_DIR=/cache
      - VERBOSE=true
      - TIMEOUT_MINUTES=30
      - PORT=10000
      - HOST=0.0.0.0
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s