version: '3.8'

services:
  llama-cpp-runner-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: llama-cpp-runner-gpu
    ports:
      - "10000:10000"
    environment:
      - MODELS_DIR=/models
      - CACHE_DIR=/cache
      - VERBOSE=true
      - TIMEOUT_MINUTES=30
      - ENABLE_GPU=true
      - GPU_LAYERS=-1
      - PORT=10000
      - HOST=0.0.0.0 
      - LOG_LEVEL=info
      - CUDA_VISIBLE_DEVICES=0
      - LD_LIBRARY_PATH=/cache/llama_cpp/build/lib:/cache/llama_cpp/build/bin:/usr/local/cuda/lib64
    volumes:
      - ./models:/models  # local mount for models
      - ./cache:/cache    # local mount for cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Longer start period for GPU initialization